### PR TITLE
Python 3.6

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by basnijholt** [comment]
@bollwyvl would you perhaps understand why the build is failing with the following error?

```
/feedstock_root/build_artefacts/linux-64/nb_conda-2.0.0-py27_0.tar.bz2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1490, in build_tree
    test(pkg, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1261, in test
    warn_on_use_of_SRC_DIR(metadata)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1210, in warn_on_use_of_SRC_DIR
    raise ValueError("In conda-build 2.1+, the work dir is removed by default before the "
ValueError: In conda-build 2.1+, the work dir is removed by default before the test scripts run.  You are using the SRC_DIR variable in your test script, but these files have been deleted.  Please see the  documentation regarding the test/source_files meta.yaml section, or pass the --no-remove-work-dir flag.

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by basnijholt** [comment]
I am reverting this PR to 2.0.0 again, since it's unreasonable to debug the tests here if even the [master](https://travis-ci.org/Anaconda-Platform/nb_conda) is failing.

**Comment by damianavila** [comment]
Thanks @basnijholt for chiming in... I think you are close... did you see the same errors locally?

**Comment by basnijholt** [comment]
I haven't run the tests locally actually.

I probably won't have time to finish this. The "Allow edits from maintainers" is checked, so if you know the solution you can just finish this MR or otherwise close it :)

**Comment by damianavila** [comment]
> I probably won't have time to finish this. The "Allow edits from maintainers" is checked, so if you know the solution you can just finish this MR or otherwise close it :)

I guess I will have some time by the end of next week. thanks for pushing forward this!

**Comment by damianavila** [comment]
New re-render with 2.3.0 and some fixes on #7 .
Thanks @basnijholt for your work here.

**Pull request closed without merging**
