### PR TITLE
Switch to noarch

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/nb_conda, if any of you has bandwidth and expertise to figure out why this is failing and #17 worked just fine over a year ago, that would be great!

I'm at a loss.

**Comment by isuruf** [comment]
You want to make this noarch?

**Comment by xylar** [comment]
@isuruf, that's a great suggestion. I'll look into it.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender.

**Comment by xylar** [comment]
@isuruf, amazing! Is this good to go? Are we going to ignore the linter?

**Comment by isuruf** [comment]
Yes we can ignore the linter

**Comment by xylar** [comment]
Thanks so much @isuruf.  I learned a lot from watching what you did here.  Hopefully, I can make use of it in other, similar feedstocks.

**Pull request merged**
